---
title: "Group Project 2"
author: "Ian and Queen"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(readr)
library(ggplot2)
library(scales)
library(dplyr)
library(tidyr)
library(readr)
library(leaflet)
library(knitr)
library(kableExtra)

#read in data
confirmed_global <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")

confirmed_us <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv")

deaths_global <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")

deaths_us <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv")
```
# Objective 1 - Global Map
Data Wrangling
```{r}
#change column name of last cumulative column to "Confirmed_Cases"
colnames(confirmed_global)[ncol(confirmed_global)] = "Confirmed_Cases"
#group table by country and calculate average lat and long for countries and sum of confirmed cases
grouped_confirmed <- confirmed_global %>% 
  select(1:4, ncol(confirmed_global)) %>% 
      group_by(Country.Region) %>%
          summarize(mean_lat=mean(Lat),
                    mean_long=mean(Long),
                    sum(Confirmed_Cases))
#change column name of last cumulative column to "Deaths"
colnames(deaths_global)[ncol(deaths_global)] = "Deaths"
#group table by country and calculate average lat and long for countries and sum of deaths
grouped_deaths <- deaths_global %>%
  select(1:4, ncol(deaths_global)) %>%
    group_by(Country.Region) %>%
      summarize(mean_lat=mean(Lat),
                mean_long=mean(Long),
                sum(Deaths))
#join the 2 data frames and remove the duplicate lat and long columns
global_stats <- merge(x=grouped_confirmed, y=grouped_deaths, by="Country.Region") %>% select(-5, -6)

```
Map Making
```{r}
global_stats$`sum(Confirmed_Cases)` = as.factor(global_stats$`sum(Confirmed_Cases)`)
#create pallette for map
pal <- colorFactor("RdYlGn", global_stats$`sum(Confirmed_Cases)`, reverse = TRUE)

#create map getting tiles from CartoDB.Positron, centered on United States
leaflet(data = global_stats) %>%
  addProviderTiles("CartoDB.Positron") %>%
  setView(lng = -100, lat = 40, zoom = 5) %>%
  addCircles(
    lat = ~mean_lat.x,
    lng = ~mean_long.x,
    #create pop ups for points on map
    popup = paste("Country:", global_stats$Country.Region, "<br>",
                  "Confirmed Cases: ", global_stats$`sum(Confirmed_Cases)`, "<br>",
                  "Deaths:" , global_stats$`sum(Deaths)`),
    radius = 500,
    color = ~pal(global_stats$`sum(Confirmed_Cases)`),
    fillOpacity = .5)
```
# Objective 2 - Narrowing Down Hot Spots  
```{r}
# Order and rank Covid-19 confirmed cases and deaths
confirmed_rank <- grouped_confirmed %>%
  select(1,4)%>%
  arrange(desc(.[, 2])) %>%
  mutate(rank = row_number()) %>%
  select(rank, everything())

death_rank <- grouped_deaths %>%
  select(1,4)%>%
  arrange(desc(.[, 2])) %>%
  mutate(rank = row_number()) %>%
  select(rank, everything())


# Merge the data frames based on rank
grouped_rank <-merge(confirmed_rank, death_rank, by = "rank") 

# Print the tables of confirmed cases using kable
kable(grouped_rank, col.names = c("Rank", "Country", "Confirmed Cases Count", "Country", "Death Count"), caption = "Top Countries") %>%
  kable_styling(fixed_thead = T) %>%
  kable_paper() %>%
  scroll_box(width = "100%", height = "500px")
```
# Objective 3 -  Zooming Into Our State 
Data Wrangling
```{r}
# Filter the table to California
ca <- confirmed_us %>%
  filter(Province_State == "California")

#change column name of last cumulative column to "Confirmed_Cases"
colnames(ca)[ncol(ca)] = "Confirmed_Cases"

# Reshape the data from wide to long format
df_long1 <- pivot_longer(ca, cols = starts_with("X"), names_to = "Date", values_to = "Confirmed")

# Format date data
df_long1$Date <- as.Date(sub("^X", "", df_long1$Date), format = "%m.%d.%y")

# Data frame for CA trajectory of confirmations
aggregated_ca <- df_long1 %>%
  group_by(Date) %>%
  summarize(Confirmed = sum(Confirmed))

# Data frame for top three city trajectories
top_ca <- ca %>%
  arrange(desc(Confirmed_Cases)) %>%
  head(3)

#change column name of last cumulative column to date
colnames(top_ca)[ncol(top_ca)] = "X3.9.23"

# Reshape the data from wide to long format
df_long2 <- pivot_longer(top_ca, cols = starts_with("X"), names_to = "Date", values_to = "Confirmed")

# Format date data
df_long2$Date <- as.Date(sub("^X", "", df_long2$Date), format = "%m.%d.%y")
```
Creating Plots
```{r}
# Create the scatter plot showing CA's trajectory for confirmations
ggplot(aggregated_ca, aes(x = Date, y = Confirmed)) +
  geom_point(size = 3) +
  labs(title = "COVID-19 Confirmations in California",
       x = "Date",
       y = "Confirmed Cases")+
  geom_vline(xintercept = as.numeric(as.Date("2021-01-29")), linetype = "dashed", color = "green") +
  geom_vline(xintercept = as.numeric(as.Date("2021-05-11")), linetype = "dashed", color = "red") +
  geom_vline(xintercept = as.numeric(as.Date("2021-11-26")), linetype = "dashed", color = "red")

# Create the scatter plot showing CA's top 3 city trajectory for confirmations
ggplot(df_long2, aes(x = Date, y = Confirmed, color = Admin2, group = Admin2)) +
  geom_point(size = 3) +
  labs(title = "Top 3 CA City's COVID-19 Confirmations",
       x = "Date",
       y = "Confirmed Cases",
      color = "City") +
  geom_vline(xintercept = as.numeric(as.Date("2021-01-29")), linetype = "dashed", color = "green") +
  geom_vline(xintercept = as.numeric(as.Date("2021-05-11")), linetype = "dashed", color = "red") +
  geom_vline(xintercept = as.numeric(as.Date("2021-11-26")), linetype = "dashed", color = "red")
```

# Objective 4 - Digging Deeper
Data Wrangling
```{r}
#Change column names to be more readable
colnames(deaths_us)[6] = "City"
colnames(deaths_us)[ncol(deaths_us)] = "Deaths"
colnames(confirmed_us)[6] = "City"
colnames(confirmed_us)[ncol(confirmed_us)] = "Confirmed"

#selecting the parts of the data frames we want to join later
usdeaths <- select(deaths_us, 1, 6:7, 12, ncol(deaths_us))
usconfirmed <- select(confirmed_us, 1, 6:7, ncol(confirmed_us))

#Create log transformations
deaths_log <- log(usdeaths$Deaths)
confirmed_log <- log(usconfirmed$Confirmed)
population_log <- log(usdeaths$Population)

#add transformations to data frames
usdeaths$Deaths_log = deaths_log
usdeaths$Population_log = population_log
usconfirmed$Confirmed_log = confirmed_log

#join data frames into one to work with when creating visualization
us_stats <- merge(x=usdeaths, y=usconfirmed, by="UID") %>% select(-8, -9)


```
Creating Plots
```{r}
library(ggplot2)
library(cowplot)
library(scales)
#create plots for use with plot_grid
#confirmed vs population plot
confpop <- ggplot(us_stats, aes(x=Population, y=Confirmed)) +
  geom_point()
confpop <- confpop + scale_x_continuous(labels=label_comma(), trans = 'log10') + scale_y_continuous(labels=label_comma(), trans = 'log10')
#deaths vs confirmed plot
deathconf <- ggplot(us_stats, aes(x=Confirmed, y=Deaths)) +
  geom_point()
deathconf <- deathconf + scale_x_continuous(labels=label_comma(), trans = 'log10') + scale_y_continuous(labels=label_comma(), trans = 'log10')

#joining the plots into one graphic
plot_grid(confpop, deathconf, labels = c("Confirmations Vs. Population","Deaths Vs. Confirmations"), align="h", hjust=-.3, vjust=.9)


```
  
  
